# Generated by Django 3.2.7 on 2021-09-12 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_rename_link_link_links'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='links',
            new_name='link',
        ),
    ]
