# Generated by Django 3.2.7 on 2021-09-12 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_rename_links_link_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='link',
            field=models.CharField(max_length=1000, verbose_name='Ссылка'),
        ),
    ]
