# Generated by Django 3.2.7 on 2021-09-13 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0004_alter_link_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ('-pub_date',), 'verbose_name': 'Ссылка', 'verbose_name_plural': 'Ссылки'},
        ),
    ]
