# Generated by Django 3.2.7 on 2021-09-13 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0005_alter_link_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ('-visit_date',), 'verbose_name': 'Ссылка', 'verbose_name_plural': 'Ссылки'},
        ),
        migrations.RenameField(
            model_name='link',
            old_name='pub_date',
            new_name='visit_date',
        ),
    ]
