# Generated by Django 3.2.7 on 2021-09-16 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0007_alter_link_visit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='visit_date',
            field=models.IntegerField(verbose_name='Время посещения'),
        ),
    ]
